from playwright.sync_api import Playwright, sync_playwright, expect
import re


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://beta.syncwise360.com/login")
    page.get_by_label("username").click()
    page.get_by_label("username").fill("QA")
    page.get_by_label("password").click()
    page.get_by_label("password").fill("Qwerty01!")
    page.get_by_label("submit").click()
    page.get_by_label("menu-icon").click()
    page.locator("li").filter(has_text="Tournaments").get_by_role("figure").click()
    page.get_by_role("button", name="Add New Tournament").click()
    page.locator("form").filter(has_text="Tournament namenumber of").locator("input[type=\"text\"]").first.click()
    page.locator("form").filter(has_text="Tournament namenumber of").locator("input[type=\"text\"]").first.fill("T1")
    page.get_by_label("Open calendar").click()
    page.get_by_label("March 31,").click()
    page.locator("div").filter(has_text=re.compile(r"^DateStart TimeEnd TimeCourseCopy Superior$")).get_by_role("textbox").nth(1).click()
    page.locator("ngx-material-timepicker-toggle").get_by_role("button").click()
    page.locator("ngx-material-timepicker-face").get_by_text("1", exact=True).click()
    page.get_by_role("button", name="PM").click()
    page.get_by_role("button", name="Ok").click()
    page.get_by_role("button", name="Save").click()
    page.locator("div").filter(has_text=re.compile(r"^DateStart TimeEnd TimeCourseCopy Superior$")).get_by_role("textbox").nth(2).click()
    page.locator("ngx-material-timepicker-toggle").get_by_role("button").click()
    page.get_by_text("6").click()
    page.get_by_role("button", name="PM").click()
    page.get_by_role("button", name="Ok").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Players").click()
    page.get_by_role("button", name="Add New Player").click()
    page.locator(".form-group > .ng-untouched").first.click()
    page.locator(".form-group > .ng-untouched").first.fill("P")
    page.locator("div:nth-child(2) > .form-group > .ng-untouched").click()
    page.locator(".form-group > .ng-valid").first.click()
    page.locator(".form-group > .ng-valid").first.fill("Player1")
    page.locator(".form-group > .ng-pristine").first.click()
    page.locator(".form-group > .ng-pristine").first.fill("p1")
    page.get_by_role("button", name="Save").click()
    page.locator("div").filter(has_text=re.compile(r"^T1 - Players \(1\)search$")).get_by_role("button").nth(1).click()
    page.locator(".form-group > .ng-untouched").first.click()
    page.locator(".form-group > .ng-untouched").first.fill("Player2")
    page.locator("div:nth-child(2) > .form-group > .ng-untouched").click()
    page.locator(".form-group > .ng-untouched").first.fill("p2")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Tee Times").click()
    page.get_by_role("button", name="Generate Tee Sheet").click()
    page.get_by_role("row", name="Hole 1A").get_by_role("button").click()
    page.get_by_role("row", name="Players HANDICAP").get_by_role("checkbox").check()
    page.get_by_role("button", name="Assign Car(s)").click()
    page.get_by_role("row", name="p2, Player2", exact=True).get_by_role("button").click()
    page.get_by_role("button", name="4").click()
    page.get_by_role("button", name="9").click()
    page.locator("#mat-dialog-6").get_by_role("button", name="Save").click()
    page.get_by_role("row", name="p1, Player1", exact=True).get_by_role("button").click()
    page.get_by_role("button", name="4", exact=True).click()
    page.get_by_role("button", name="9", exact=True).click()
    page.locator("#mat-dialog-7").get_by_role("button", name="Save").click()
    page.locator("#mat-dialog-5").get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Save").click()
    page.locator("div").filter(has_text=re.compile(r"^T1 - Tee Times$")).get_by_role("button").click()
    page.get_by_label("menu-icon").click()
    page.locator("div").filter(has_text=re.compile(r"^Asset Tracker$")).click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
